# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Program Files\Python 2.7\MCmapper\code\mcmap.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MCMIR_Screen(object):
    def setupUi(self, MCMIR_Screen):
        MCMIR_Screen.setObjectName(_fromUtf8("MCMIR_Screen"))
        MCMIR_Screen.resize(792, 495)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/png/Map_Item_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MCMIR_Screen.setWindowIcon(icon)
        self.horizontalLayout_4 = QtGui.QHBoxLayout(MCMIR_Screen)
        self.horizontalLayout_4.setMargin(5)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.splitter = QtGui.QSplitter(MCMIR_Screen)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.verticalLayoutWidget = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.LeftPanel = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.LeftPanel.setObjectName(_fromUtf8("LeftPanel"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.LocateFolderButton = QtGui.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LocateFolderButton.sizePolicy().hasHeightForWidth())
        self.LocateFolderButton.setSizePolicy(sizePolicy)
        self.LocateFolderButton.setMinimumSize(QtCore.QSize(60, 25))
        self.LocateFolderButton.setMaximumSize(QtCore.QSize(60, 25))
        self.LocateFolderButton.setObjectName(_fromUtf8("LocateFolderButton"))
        self.horizontalLayout.addWidget(self.LocateFolderButton)
        self.TopTreeLabel = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TopTreeLabel.sizePolicy().hasHeightForWidth())
        self.TopTreeLabel.setSizePolicy(sizePolicy)
        self.TopTreeLabel.setMinimumSize(QtCore.QSize(100, 25))
        self.TopTreeLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        self.TopTreeLabel.setObjectName(_fromUtf8("TopTreeLabel"))
        self.horizontalLayout.addWidget(self.TopTreeLabel)
        self.LeftPanel.addLayout(self.horizontalLayout)
        self.MapTree = QtGui.QTreeWidget(self.verticalLayoutWidget)
        self.MapTree.setMinimumSize(QtCore.QSize(250, 450))
        self.MapTree.setAnimated(True)
        self.MapTree.setHeaderHidden(False)
        self.MapTree.setColumnCount(2)
        self.MapTree.setObjectName(_fromUtf8("MapTree"))
        self.MapTree.headerItem().setText(0, _fromUtf8("Saves"))
        self.MapTree.header().setVisible(True)
        self.MapTree.header().setDefaultSectionSize(100)
        self.MapTree.header().setHighlightSections(True)
        self.MapTree.header().setMinimumSectionSize(10)
        self.MapTree.header().setStretchLastSection(True)
        self.LeftPanel.addWidget(self.MapTree)
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.MiddlePanel = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.MiddlePanel.setSpacing(2)
        self.MiddlePanel.setObjectName(_fromUtf8("MiddlePanel"))
        self.TopMiddleLabel = QtGui.QLabel(self.verticalLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TopMiddleLabel.sizePolicy().hasHeightForWidth())
        self.TopMiddleLabel.setSizePolicy(sizePolicy)
        self.TopMiddleLabel.setMinimumSize(QtCore.QSize(0, 25))
        self.TopMiddleLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        self.TopMiddleLabel.setTextFormat(QtCore.Qt.RichText)
        self.TopMiddleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TopMiddleLabel.setObjectName(_fromUtf8("TopMiddleLabel"))
        self.MiddlePanel.addWidget(self.TopMiddleLabel)
        self.RenderGB = QtGui.QFrame(self.verticalLayoutWidget_4)
        self.RenderGB.setObjectName(_fromUtf8("RenderGB"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.RenderGB)
        self.verticalLayout_5.setMargin(2)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.RenTogGB = QtGui.QGroupBox(self.RenderGB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RenTogGB.sizePolicy().hasHeightForWidth())
        self.RenTogGB.setSizePolicy(sizePolicy)
        self.RenTogGB.setMinimumSize(QtCore.QSize(240, 200))
        self.RenTogGB.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.RenTogGB.setFlat(True)
        self.RenTogGB.setObjectName(_fromUtf8("RenTogGB"))
        self.gridLayout_3 = QtGui.QGridLayout(self.RenTogGB)
        self.gridLayout_3.setMargin(1)
        self.gridLayout_3.setSpacing(1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.RenTogButton = QtGui.QPushButton(self.RenTogGB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RenTogButton.sizePolicy().hasHeightForWidth())
        self.RenTogButton.setSizePolicy(sizePolicy)
        self.RenTogButton.setMinimumSize(QtCore.QSize(90, 35))
        self.RenTogButton.setMaximumSize(QtCore.QSize(90, 35))
        self.RenTogButton.setObjectName(_fromUtf8("RenTogButton"))
        self.gridLayout_3.addWidget(self.RenTogButton, 1, 0, 1, 1)
        self.OptsGB = QtGui.QGroupBox(self.RenTogGB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OptsGB.sizePolicy().hasHeightForWidth())
        self.OptsGB.setSizePolicy(sizePolicy)
        self.OptsGB.setMinimumSize(QtCore.QSize(120, 90))
        self.OptsGB.setMaximumSize(QtCore.QSize(16777215, 90))
        self.OptsGB.setObjectName(_fromUtf8("OptsGB"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.OptsGB)
        self.verticalLayout_3.setMargin(3)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.BoundBoxCB = QtGui.QCheckBox(self.OptsGB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BoundBoxCB.sizePolicy().hasHeightForWidth())
        self.BoundBoxCB.setSizePolicy(sizePolicy)
        self.BoundBoxCB.setObjectName(_fromUtf8("BoundBoxCB"))
        self.verticalLayout_3.addWidget(self.BoundBoxCB)
        self.MapNameCB = QtGui.QCheckBox(self.OptsGB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MapNameCB.sizePolicy().hasHeightForWidth())
        self.MapNameCB.setSizePolicy(sizePolicy)
        self.MapNameCB.setObjectName(_fromUtf8("MapNameCB"))
        self.verticalLayout_3.addWidget(self.MapNameCB)
        self.SpawnpointCB = QtGui.QCheckBox(self.OptsGB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpawnpointCB.sizePolicy().hasHeightForWidth())
        self.SpawnpointCB.setSizePolicy(sizePolicy)
        self.SpawnpointCB.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.SpawnpointCB.setObjectName(_fromUtf8("SpawnpointCB"))
        self.verticalLayout_3.addWidget(self.SpawnpointCB)
        self.SkipCB = QtGui.QCheckBox(self.OptsGB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SkipCB.sizePolicy().hasHeightForWidth())
        self.SkipCB.setSizePolicy(sizePolicy)
        self.SkipCB.setCheckable(True)
        self.SkipCB.setChecked(True)
        self.SkipCB.setObjectName(_fromUtf8("SkipCB"))
        self.verticalLayout_3.addWidget(self.SkipCB)
        self.gridLayout_3.addWidget(self.OptsGB, 1, 1, 1, 1)
        self.DimGB = QtGui.QGroupBox(self.RenTogGB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DimGB.sizePolicy().hasHeightForWidth())
        self.DimGB.setSizePolicy(sizePolicy)
        self.DimGB.setMinimumSize(QtCore.QSize(90, 0))
        self.DimGB.setMaximumSize(QtCore.QSize(90, 16777215))
        self.DimGB.setObjectName(_fromUtf8("DimGB"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.DimGB)
        self.verticalLayout_2.setMargin(3)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.MainDimRB = QtGui.QRadioButton(self.DimGB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainDimRB.sizePolicy().hasHeightForWidth())
        self.MainDimRB.setSizePolicy(sizePolicy)
        self.MainDimRB.setChecked(True)
        self.MainDimRB.setObjectName(_fromUtf8("MainDimRB"))
        self.verticalLayout_2.addWidget(self.MainDimRB)
        self.NetherDimRB = QtGui.QRadioButton(self.DimGB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NetherDimRB.sizePolicy().hasHeightForWidth())
        self.NetherDimRB.setSizePolicy(sizePolicy)
        self.NetherDimRB.setObjectName(_fromUtf8("NetherDimRB"))
        self.verticalLayout_2.addWidget(self.NetherDimRB)
        self.EndDimRB = QtGui.QRadioButton(self.DimGB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EndDimRB.sizePolicy().hasHeightForWidth())
        self.EndDimRB.setSizePolicy(sizePolicy)
        self.EndDimRB.setObjectName(_fromUtf8("EndDimRB"))
        self.verticalLayout_2.addWidget(self.EndDimRB)
        self.gridLayout_3.addWidget(self.DimGB, 0, 0, 1, 1)
        self.ScaleGB = QtGui.QGroupBox(self.RenTogGB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ScaleGB.sizePolicy().hasHeightForWidth())
        self.ScaleGB.setSizePolicy(sizePolicy)
        self.ScaleGB.setMinimumSize(QtCore.QSize(120, 0))
        self.ScaleGB.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ScaleGB.setObjectName(_fromUtf8("ScaleGB"))
        self.gridLayout_4 = QtGui.QGridLayout(self.ScaleGB)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.ScaleAllRB = QtGui.QRadioButton(self.ScaleGB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ScaleAllRB.sizePolicy().hasHeightForWidth())
        self.ScaleAllRB.setSizePolicy(sizePolicy)
        self.ScaleAllRB.setChecked(True)
        self.ScaleAllRB.setObjectName(_fromUtf8("ScaleAllRB"))
        self.gridLayout_4.addWidget(self.ScaleAllRB, 0, 0, 1, 1)
        self.Scale1RB = QtGui.QRadioButton(self.ScaleGB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Scale1RB.sizePolicy().hasHeightForWidth())
        self.Scale1RB.setSizePolicy(sizePolicy)
        self.Scale1RB.setObjectName(_fromUtf8("Scale1RB"))
        self.gridLayout_4.addWidget(self.Scale1RB, 0, 1, 1, 1)
        self.Scale3RB = QtGui.QRadioButton(self.ScaleGB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Scale3RB.sizePolicy().hasHeightForWidth())
        self.Scale3RB.setSizePolicy(sizePolicy)
        self.Scale3RB.setObjectName(_fromUtf8("Scale3RB"))
        self.gridLayout_4.addWidget(self.Scale3RB, 0, 2, 1, 1)
        self.Scale0RB = QtGui.QRadioButton(self.ScaleGB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Scale0RB.sizePolicy().hasHeightForWidth())
        self.Scale0RB.setSizePolicy(sizePolicy)
        self.Scale0RB.setObjectName(_fromUtf8("Scale0RB"))
        self.gridLayout_4.addWidget(self.Scale0RB, 1, 0, 1, 1)
        self.Scale2RB = QtGui.QRadioButton(self.ScaleGB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Scale2RB.sizePolicy().hasHeightForWidth())
        self.Scale2RB.setSizePolicy(sizePolicy)
        self.Scale2RB.setObjectName(_fromUtf8("Scale2RB"))
        self.gridLayout_4.addWidget(self.Scale2RB, 1, 1, 1, 1)
        self.Scale4RB = QtGui.QRadioButton(self.ScaleGB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Scale4RB.sizePolicy().hasHeightForWidth())
        self.Scale4RB.setSizePolicy(sizePolicy)
        self.Scale4RB.setObjectName(_fromUtf8("Scale4RB"))
        self.gridLayout_4.addWidget(self.Scale4RB, 1, 2, 1, 1)
        self.gridLayout_3.addWidget(self.ScaleGB, 0, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.RenTogGB)
        self.RenSepGB = QtGui.QGroupBox(self.RenderGB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RenSepGB.sizePolicy().hasHeightForWidth())
        self.RenSepGB.setSizePolicy(sizePolicy)
        self.RenSepGB.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.RenSepGB.setFlat(True)
        self.RenSepGB.setObjectName(_fromUtf8("RenSepGB"))
        self.gridLayout = QtGui.QGridLayout(self.RenSepGB)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.RenPreButton = QtGui.QPushButton(self.RenSepGB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RenPreButton.sizePolicy().hasHeightForWidth())
        self.RenPreButton.setSizePolicy(sizePolicy)
        self.RenPreButton.setMinimumSize(QtCore.QSize(90, 25))
        self.RenPreButton.setMaximumSize(QtCore.QSize(100, 25))
        self.RenPreButton.setObjectName(_fromUtf8("RenPreButton"))
        self.gridLayout.addWidget(self.RenPreButton, 0, 0, 1, 1)
        self.label = QtGui.QLabel(self.RenSepGB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(70, 25))
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.RenEacButton = QtGui.QPushButton(self.RenSepGB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RenEacButton.sizePolicy().hasHeightForWidth())
        self.RenEacButton.setSizePolicy(sizePolicy)
        self.RenEacButton.setMinimumSize(QtCore.QSize(90, 0))
        self.RenEacButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.RenEacButton.setObjectName(_fromUtf8("RenEacButton"))
        self.gridLayout.addWidget(self.RenEacButton, 1, 0, 1, 1)
        self.RenSepSB = QtGui.QSpinBox(self.RenSepGB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RenSepSB.sizePolicy().hasHeightForWidth())
        self.RenSepSB.setSizePolicy(sizePolicy)
        self.RenSepSB.setMinimumSize(QtCore.QSize(70, 25))
        self.RenSepSB.setMaximumSize(QtCore.QSize(100, 25))
        self.RenSepSB.setFrame(True)
        self.RenSepSB.setAlignment(QtCore.Qt.AlignCenter)
        self.RenSepSB.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.RenSepSB.setMinimum(1)
        self.RenSepSB.setMaximum(16)
        self.RenSepSB.setObjectName(_fromUtf8("RenSepSB"))
        self.gridLayout.addWidget(self.RenSepSB, 1, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.RenSepGB)
        spacerItem = QtGui.QSpacerItem(20, 999999999, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.OtherGB = QtGui.QGroupBox(self.RenderGB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OtherGB.sizePolicy().hasHeightForWidth())
        self.OtherGB.setSizePolicy(sizePolicy)
        self.OtherGB.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.OtherGB.setFlat(True)
        self.OtherGB.setObjectName(_fromUtf8("OtherGB"))
        self.gridLayout_2 = QtGui.QGridLayout(self.OtherGB)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.AlignButton = QtGui.QPushButton(self.OtherGB)
        self.AlignButton.setObjectName(_fromUtf8("AlignButton"))
        self.gridLayout_2.addWidget(self.AlignButton, 0, 0, 1, 1)
        self.ForumThreadLabel = QtGui.QLabel(self.OtherGB)
        self.ForumThreadLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ForumThreadLabel.setOpenExternalLinks(True)
        self.ForumThreadLabel.setObjectName(_fromUtf8("ForumThreadLabel"))
        self.gridLayout_2.addWidget(self.ForumThreadLabel, 0, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.OtherGB)
        self.MiddlePanel.addWidget(self.RenderGB)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.RightPanel = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.RightPanel.setSpacing(2)
        self.RightPanel.setObjectName(_fromUtf8("RightPanel"))
        self.TopDisplayLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TopDisplayLabel.sizePolicy().hasHeightForWidth())
        self.TopDisplayLabel.setSizePolicy(sizePolicy)
        self.TopDisplayLabel.setMinimumSize(QtCore.QSize(260, 25))
        self.TopDisplayLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        self.TopDisplayLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TopDisplayLabel.setObjectName(_fromUtf8("TopDisplayLabel"))
        self.RightPanel.addWidget(self.TopDisplayLabel)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem1 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.PreviewDisplay = QtGui.QGraphicsView(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PreviewDisplay.sizePolicy().hasHeightForWidth())
        self.PreviewDisplay.setSizePolicy(sizePolicy)
        self.PreviewDisplay.setMinimumSize(QtCore.QSize(260, 260))
        self.PreviewDisplay.setMaximumSize(QtCore.QSize(260, 260))
        self.PreviewDisplay.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.PreviewDisplay.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.PreviewDisplay.setObjectName(_fromUtf8("PreviewDisplay"))
        self.horizontalLayout_3.addWidget(self.PreviewDisplay)
        spacerItem2 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.RightPanel.addLayout(self.horizontalLayout_3)
        self.frame = QtGui.QFrame(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(260, 45))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setMargin(3)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.MapInfoLabelLeft = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MapInfoLabelLeft.sizePolicy().hasHeightForWidth())
        self.MapInfoLabelLeft.setSizePolicy(sizePolicy)
        self.MapInfoLabelLeft.setMinimumSize(QtCore.QSize(125, 40))
        self.MapInfoLabelLeft.setMaximumSize(QtCore.QSize(16777215, 40))
        self.MapInfoLabelLeft.setAlignment(QtCore.Qt.AlignCenter)
        self.MapInfoLabelLeft.setObjectName(_fromUtf8("MapInfoLabelLeft"))
        self.horizontalLayout_2.addWidget(self.MapInfoLabelLeft)
        self.MapInfoLabelRight = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MapInfoLabelRight.sizePolicy().hasHeightForWidth())
        self.MapInfoLabelRight.setSizePolicy(sizePolicy)
        self.MapInfoLabelRight.setMinimumSize(QtCore.QSize(125, 40))
        self.MapInfoLabelRight.setMaximumSize(QtCore.QSize(16777215, 40))
        self.MapInfoLabelRight.setAlignment(QtCore.Qt.AlignCenter)
        self.MapInfoLabelRight.setObjectName(_fromUtf8("MapInfoLabelRight"))
        self.horizontalLayout_2.addWidget(self.MapInfoLabelRight)
        self.RightPanel.addWidget(self.frame)
        self.Prompt_Text = QtGui.QTextBrowser(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Prompt_Text.sizePolicy().hasHeightForWidth())
        self.Prompt_Text.setSizePolicy(sizePolicy)
        self.Prompt_Text.setMinimumSize(QtCore.QSize(260, 120))
        self.Prompt_Text.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Prompt_Text.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.Prompt_Text.setObjectName(_fromUtf8("Prompt_Text"))
        self.RightPanel.addWidget(self.Prompt_Text)
        self.horizontalLayout_4.addWidget(self.splitter)

        self.retranslateUi(MCMIR_Screen)
        QtCore.QMetaObject.connectSlotsByName(MCMIR_Screen)

    def retranslateUi(self, MCMIR_Screen):
        MCMIR_Screen.setWindowTitle(_translate("MCMIR_Screen", "Map Item Renderer", None))
        self.LocateFolderButton.setToolTip(_translate("MCMIR_Screen", "Locate Save Folder", None))
        self.LocateFolderButton.setText(_translate("MCMIR_Screen", "Folder", None))
        self.TopTreeLabel.setText(_translate("MCMIR_Screen", "Folder Location", None))
        self.MapTree.headerItem().setText(1, _translate("MCMIR_Screen", "Notes", None))
        self.TopMiddleLabel.setToolTip(_translate("MCMIR_Screen", "By Tailbones", None))
        self.TopMiddleLabel.setText(_translate("MCMIR_Screen", "Map Item Renderer", None))
        self.RenTogGB.setTitle(_translate("MCMIR_Screen", "Render together", None))
        self.RenTogButton.setToolTip(_translate("MCMIR_Screen", "Renders all the maps of the selected world as one", None))
        self.RenTogButton.setText(_translate("MCMIR_Screen", "Render\n"
"Together", None))
        self.OptsGB.setTitle(_translate("MCMIR_Screen", "Options", None))
        self.BoundBoxCB.setToolTip(_translate("MCMIR_Screen", "Draws a box around each map", None))
        self.BoundBoxCB.setText(_translate("MCMIR_Screen", "Bounding Box", None))
        self.MapNameCB.setToolTip(_translate("MCMIR_Screen", "Labels the maps", None))
        self.MapNameCB.setText(_translate("MCMIR_Screen", "Map Name", None))
        self.SpawnpointCB.setToolTip(_translate("MCMIR_Screen", "Mark the world spawnpoint", None))
        self.SpawnpointCB.setText(_translate("MCMIR_Screen", "Mark Spawnpoint", None))
        self.SkipCB.setToolTip(_translate("MCMIR_Screen", "Skip blank maps", None))
        self.SkipCB.setText(_translate("MCMIR_Screen", "Skip Blank Maps", None))
        self.DimGB.setTitle(_translate("MCMIR_Screen", "Dimension", None))
        self.MainDimRB.setToolTip(_translate("MCMIR_Screen", "Main Dimension", None))
        self.MainDimRB.setText(_translate("MCMIR_Screen", "Main", None))
        self.NetherDimRB.setToolTip(_translate("MCMIR_Screen", "Nether Dimension", None))
        self.NetherDimRB.setText(_translate("MCMIR_Screen", "Nether", None))
        self.EndDimRB.setToolTip(_translate("MCMIR_Screen", "End Dimension", None))
        self.EndDimRB.setText(_translate("MCMIR_Screen", "End", None))
        self.ScaleGB.setTitle(_translate("MCMIR_Screen", "Scale", None))
        self.ScaleAllRB.setToolTip(_translate("MCMIR_Screen", "All", None))
        self.ScaleAllRB.setText(_translate("MCMIR_Screen", "All", None))
        self.Scale1RB.setToolTip(_translate("MCMIR_Screen", "1 pixel = 2x2 blocks", None))
        self.Scale1RB.setText(_translate("MCMIR_Screen", "1", None))
        self.Scale3RB.setToolTip(_translate("MCMIR_Screen", "1 pixel = 8x8 blocks", None))
        self.Scale3RB.setText(_translate("MCMIR_Screen", "3", None))
        self.Scale0RB.setToolTip(_translate("MCMIR_Screen", "1 pixel = 1 block", None))
        self.Scale0RB.setText(_translate("MCMIR_Screen", "0", None))
        self.Scale2RB.setToolTip(_translate("MCMIR_Screen", "1 pixel = 4x4 blocks", None))
        self.Scale2RB.setText(_translate("MCMIR_Screen", "2", None))
        self.Scale4RB.setToolTip(_translate("MCMIR_Screen", "1 pixel = 16x16 blocks", None))
        self.Scale4RB.setText(_translate("MCMIR_Screen", "4", None))
        self.RenSepGB.setTitle(_translate("MCMIR_Screen", "Render Seperately", None))
        self.RenPreButton.setToolTip(_translate("MCMIR_Screen", "Renders the preview", None))
        self.RenPreButton.setText(_translate("MCMIR_Screen", "Render Preview", None))
        self.label.setToolTip(_translate("MCMIR_Screen", "Adjusts the size of render\n"
"1 gives an image size of 256 x 256\n"
"2 gives an image size of 512 x 512\n"
"and so on", None))
        self.label.setText(_translate("MCMIR_Screen", "Scale Factor", None))
        self.RenEacButton.setToolTip(_translate("MCMIR_Screen", "Renders each map of the selected world seperately", None))
        self.RenEacButton.setText(_translate("MCMIR_Screen", "Render Each", None))
        self.RenSepSB.setToolTip(_translate("MCMIR_Screen", "Adjusts the size of render\n"
"1 gives an image size of 256 x 256\n"
"2 gives an image size of 512 x 512\n"
"and so on", None))
        self.OtherGB.setTitle(_translate("MCMIR_Screen", "Other", None))
        self.AlignButton.setToolTip(_translate("MCMIR_Screen", "Determines where map centers should be to prevent overlap", None))
        self.AlignButton.setText(_translate("MCMIR_Screen", "Grid Alignment Tool", None))
        self.ForumThreadLabel.setToolTip(_translate("MCMIR_Screen", "Opens link to related forum thread", None))
        self.ForumThreadLabel.setText(_translate("MCMIR_Screen", "<html><head/><body><p><a href=\"http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/1263754-minecraft-map-item-renderer\"><span style=\" text-decoration: underline; color:#0000ff;\">Forum Thread</span></a></p></body></html>", None))
        self.TopDisplayLabel.setText(_translate("MCMIR_Screen", "Preview", None))
        self.MapInfoLabelLeft.setText(_translate("MCMIR_Screen", "Left Info", None))
        self.MapInfoLabelRight.setText(_translate("MCMIR_Screen", "Right Info", None))

